#%RAML 1.0 AnnotationTypeDeclaration
allowedTargets: [methods]
properties:
  usage:
    description: the API is used for documenting onlineshopping
    default: get
  controller:
    description: developers should be informed about metadata
    properties:
      url:
        description: dev.net is the url
        default: href
      protocol:
        description: 
        default: 
      visibility?:
        description: 
        type:
        default: 
      methodusage:
        description: 
        type:
        default:  
    

      
