#%RAML 1.0 NamedExample
[
 {
  "addressid": 4144,
  "amount": 4568,
},
{
  "discountid": 458,
  "orderid": 4589,
  "status": "okay",
  "userid": 45896
                },
  {
  "addressid": 4144,
  "amount": 4568,
},
{
  "discountid": 458,
  "orderid": 4589,
  "status": "okay",
  "userid": 45896
                }
]