#%RAML 1.0 NamedExample
 [{
                    "productid": 110,
                    "categoryid": 18,
                    "name": "BARA",
                    "description": "it's not ZARA, it was always BARA. #BEBARA",
                    "video_url": "https://www.youtube.com/embed/qVpk4eeTqag",
                    "price": 999
                  },
                  {
                    "productid": 111,
                    "categoryid": 21,
                    "name": "Nike",
                    "description": "its the best shoes you will find in the world",
                    "video_url": "https://www.youtube.com/embed/qVpk4eeTqag",
                    "price": 1500
                  },
                  {
                    "productid": 112,
                    "categoryid": 22,
                    "name": "CHCH",
                    "description": "ultimate femme fatale fragrance",
                    "video_url": "https://www.carolinaherrera.com/us/en/fragrances/ch-carolina-herrera/",
                    "price": 1000
                  }]