#%RAML 1.0 NamedExample
      {"productid": 110,
        "categoryid": 18,
        "name": "BARA",
        "description": "it's not ZARA, it was always BARA. #BEBARA",
        "video_url": "https://www.youtube.com/embed/qVpk4eeTqag",
        "price": 999}