#%RAML 1.0 NamedExample
              {
                "categoryid": 145,
                "description": "test",
                "name": "test",
                "price":4589,
                "productid": 488,
                "video_url": "test.com"
              }