#%RAML 1.0 NamedExample
[     
                        { "productid": 100,
                        "categoryid": 10,
                        "name": "Amazon laptop",
                        "description": "best batter life, 15' laptop, with a 1-year warranty",
                        "video_url": "https://www.youtube.com/embed/Ic-Y3osvnFk",
                        "price": 10000},
                        {
                     "productid": 102,
                      "categoryid": 12,
                      "name": "Google Home",
                     "description": "Google home lets you automate stuff. It's cool.",
                      "video_url": "https://www.youtube.com/embed/r0iLfAV0pIg",
                      "price": 9821
                    },
                    {
                      "productid": 103,
                      "categoryid": 16,
                      "name": "amazon essentials 15' laptop cover",
                     "description": "The best you can get around in a handy design and funky look.",
                     "video_url": "https://www.youtube.com/embed/m1IdWMIoSDc",
                     "price": 200
                    },
                    {
                      "productid": 104,
                      "categoryid": 11,
                      "name": "Dell Alienware 007B",
                      "description": "The alienware 007B is as it is named, the beast type.",
                      "video_url": "https://www.youtube.com/embed/5kFEg2fRxA4",
                      "price": 1600
                     }]