#%RAML 1.0 NamedExample
      [
      {   "userid": 900,
          "email": "faye@hotmail.com",
           "username": "fayz"
          },
          {
            "userid": 1000,
            "email": "Betty@gmail.com",
             "username": "Bitaniya"
        } 
      ]